
services:
  # MySQL service
  mysql:
    image: mariadb:10.5
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: mydb       
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    restart: always

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql  
      PMA_PORT: 3306   
    ports:
      - "8080:80"  
    depends_on:
      - mysql
    volumes:
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - backend
    restart: always

  # PHP-FPM 7.4 service
  php-fpm:
    image: php:7.4-fpm
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html  
      - ./config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
    restart: always

  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  
      - ./app:/var/www/html  
    ports:
      - "80:80"  
    depends_on:
      - php-fpm  
      - phpmyadmin
    networks:
      - backend
    restart: always

volumes:
  mysql-data:

networks:
  backend:
    driver: bridge
