

services:
  # MySQL service
  mysql:
    image: mariadb:10.5
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: mydb       
    volumes:
      - mysql-data:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/my.cnf
    networks:
      - backend
    ports:
    - "3306:3306"
    restart: always

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql  
      PMA_PORT: 3306   
    ports:
      - "8080:80"  
    depends_on:
      - mysql
    volumes:
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - backend
    restart: always

  # PHP-FPM 7.4 service
  php-fpm-7.4:
    image: php:7.4-fpm
    container_name: php-fpm-7.4
    volumes:
      - ./app:/var/www/html  
      - ./config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
    restart: always

  # PHP-FPM 8.0 service
  php-fpm-8.0:
    image: php:8.0-fpm
    container_name: php-fpm-8.0
    volumes:
      - ./app:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
    restart: always

  # PHP-FPM 8.1 service
  php-fpm-8.1:
    image: php:8.1-fpm
    container_name: php-fpm-8.1
    volumes:
      - ./app:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
    restart: always

  # PHP-FPM 8.2 service
  php-fpm-8.2:
    image: php:8.2-fpm
    container_name: php-fpm-8.2
    volumes:
      - ./app:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
    restart: always


  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  
      - ./app:/var/www/html  
    ports:
      - "80:80"  
    depends_on:
      - php-fpm-7.4  
      - php-fpm-8.0
      - php-fpm-8.1
      - php-fpm-8.2  
      - phpmyadmin
    networks:
      - backend
    restart: always

volumes:
  mysql-data:

networks:
  backend:
    driver: bridge
